routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth'], function () {
    // ------------------ Authentication Routes...
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::get('logout', 'LoginController@logout');
});

Route::get('province/get-cities', 'ProvinceController@getCities');

Route::get('login', 'Back\MainController@login')->name('login');

// ------------------ Admin Part Routes
Route::group(['namespace' => 'Back', 'as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'Admin']], function () {

    // ------------------ MainController
    Route::get('/', 'MainController@index')->name('dashboard');
    Route::get('settings', 'MainController@settings')->name('settings');
    Route::post('settings/profile', 'MainController@profile')->name('settings.profile');
    Route::post('settings/socials', 'MainController@socials')->name('settings.socials');
    Route::post('settings/sizes', 'MainController@sizes')->name('settings.sizes');
    Route::post('settings/information', 'MainController@information')->name('settings.information');
    Route::get('get-tags', 'MainController@get_tags');

    Route::get('notifications', 'MainController@notifications')->name('notifications');

    Route::get('file-manager', 'MainController@fileManager')->name('file-manager');
    Route::get('file-manager-iframe', 'MainController@fileManagerIframe')->name('file-manager-iframe');

    // ------------------ users
    Route::resource('users', 'UserController');
    Route::get('users/export/excel', 'UserController@export')->name('users.export');

    // ------------------ widgets
    Route::resource('widgets', 'WidgetController');

    // ------------------ pictorials
    Route::resource('pictorials', 'PictorialController')->except('show');
    Route::post('pictorials/image-store', 'PictorialController@image_store');
    Route::post('pictorials/image-delete', 'PictorialController@image_delete');
    Route::get('pictorial/categories', 'PictorialController@categories')->name('pictorials.categories.index');


    // ------------------ posts
    Route::resource('posts', 'PostController')->except(['show']);
    Route::get('post/categories', 'PostController@categories')->name('posts.categories.index');

    // ------------------ videos
    Route::resource('videos', 'VideoController')->except(['show']);
    Route::get('video/categories', 'VideoController@categories')->name('videos.categories.index');


    // ------------------ categories
    Route::resource('categories', 'CategoryController')->only(['update', 'destroy', 'store']);
    Route::post('categories/sort', 'CategoryController@sort');


    // ------------------ pages
    Route::resource('pages', 'PageController')->except(['show']);

    // ------------------ menus
    Route::resource('menus', 'MenuController')->except(['edit']);
    Route::post('menus/sort', 'MenuController@sort');

    // ------------------ sliders
    Route::resource('sliders', 'SliderController')->except(['show']);
    Route::post('sliders/sort', 'SliderController@sort');

    // ------------------ banners
    Route::resource('banners', 'BannerController')->except(['show']);
    Route::post('banners/sort', 'BannerController@sort');

    // ------------------ links
    Route::resource('links', 'LinkController')->except(['show']);
    Route::post('links/sort', 'LinkController@sort');
    Route::get('links/groups', 'LinkController@groups')->name('links.groups.index');
    Route::put('links/groups/update', 'LinkController@updateGroups')->name('links.groups.update');

    // ------------------ contacts
    Route::resource('contacts', 'ContactController')->only(['index', 'show', 'destroy']);

    // ------------------ newsletters
    Route::resource('newsletters', 'NewsletterController')->only(['index', 'destroy']);
    Route::get('newsletters/export/excel', 'NewsletterController@export')->name('newsletters.export');

    // ------------------ comments
    Route::resource('comments', 'CommentController')->only(['index', 'show', 'destroy', 'update']);
});

// ------------------ Front Part Routes
Route::group(['namespace' => 'Front', 'as' => 'front.'], function () {
    // ------------------ MainController
    Route::get('/', 'MainController@index')->name('index');
    Route::get('/get-new-captcha', 'MainController@captcha');

    // ------------------ pictorials
    Route::resource('pictorials', 'PictorialController')->only(['index', 'show']);
    Route::get('pictorials/category/{category}', 'PictorialController@category')->name('pictorials.category');
    Route::get('pictorials/category-pictorials/{category}', 'PictorialController@categoryPictorials')->name('pictorials.category-pictorials');
    Route::post('pictorials/{pictorial}/comments', 'PictorialController@comments')->name('pictorial.comments');

    // ------------------ posts
    Route::resource('posts', 'PostController')->only(['index', 'show']);
    Route::get('posts/category/{category}', 'PostController@category')->name('posts.category');
    Route::post('posts/{post}/comments', 'PostController@comments')->name('post.comments');

    // ------------------ videos
    Route::resource('videos', 'VideoController')->only(['index', 'show']);
    Route::get('videos/category/{category}', 'VideoController@category')->name('videos.category');
    Route::post('videos/{video}/comments', 'VideoController@comments')->name('video.comments');
    Route::get('pages/{pages}', 'PageController@show')->name('pages.show');

    // ------------------ newsletters
    Route::resource('newsletters', 'NewsletterController')->only(['store']);

    // ------------------ contacts
    Route::resource('contact', 'ContactController')->only(['index', 'store']);
});

Route::get('/about', function () {
    return view('front.about');
});

resources/views/back/partials/settings/information-tab.blade.php
<div class="tab-pane" id="information" aria-labelledby="information-tab" role="tabpanel">
    <!-- users edit Info form start -->
    <form id="information-form" action="{{ route('admin.settings.information') }}" method="POST">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>عنوان وبسایت</label>
                        <input type="text" name="info_site_title" class="form-control" value="{{ option('info_site_title') }}">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <fieldset class="form-group">
                    <label for="basicInputFile">آیکون</label>
                    <div class="custom-file">
                        <input type="file" accept="image/*" name="info_icon" class="custom-file-input">
                        <label class="custom-file-label" for="inputGroupFile01">{{ option('info_icon') }}</label>
                        <p><small>بهترین اندازه <span class="text-danger">{{ option('sizes_icon') }}</span> پیکسل میباشد.</small></p>

                    </div>
                </fieldset>
                
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <fieldset class="form-group">
                    <label for="basicInputFile">لوگوی شرکت</label>
                    <div class="custom-file">
                        <input type="file" accept="image/*" name="info_logo" class="custom-file-input">
                        <label class="custom-file-label" for="inputGroupFile01">{{ option('info_logo') }}</label>
                        <p><small>بهترین اندازه <span class="text-danger">{{ option('sizes_logo') }}</span> پیکسل میباشد.</small></p>
                    </div>
                </fieldset>
                
                
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>تلفن</label>
                        <input type="text" name="info_tel" class="form-control" value="{{ option('info_tel') }}" >
                    </div>
                </div>
                
            </div>
        </div>
        
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>فکس</label>
                        <input type="text" name="info_fax" class="form-control" value="{{ option('info_fax') }}">
                    </div>
                </div>
                
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>کد پستی</label>
                        <input type="text" name="info_postal_code" class="form-control" value="{{ option('info_postal_code') }}">
                    </div>
                </div>
            </div>
        </div>
       
        <div class="row">
            <div class="col-md-6">
                <fieldset class="form-group">
                    <label>کلمات کلیدی</label>
                    <input id="tags" type="text" name="info_tags" class="form-control" value="{{ option('info_tags') }}">
                </fieldset>
                
            </div>
            <div class="col-md-6">
                <fieldset class="form-group">
                    <label>توضیحات کوتاه</label>
                    <textarea name="info_short_description" class="form-control" rows="3">{{ option('info_short_description') }}</textarea>
                </fieldset>
            </div>
        </div>

        <div class="row">

            <div class="col-md-6">
                <fieldset class="form-group">
                    <label>آدرس</label>
                    <textarea  name="info_address" class="form-control" rows="3">{{ option('info_address') }}</textarea>
                </fieldset>
            </div>
            <div class="col-md-6">
                <fieldset class="form-group">
                    <label>متن فوتر</label>
                    <textarea  name="info_footer_text" class="form-control" rows="3">{{ option('info_footer_text') }}</textarea>
                </fieldset>
            </div>
            <div class="col-md-6">
                <fieldset class="form-group">
                    <label>اسکریپت های اضافه</label>
                    <textarea  name="info_scripts" class="form-control ltr" rows="3">{{ option('info_scripts') }}</textarea>
                </fieldset>
            </div>
            <div class="col-md-6">
                <fieldset class="form-group">
                    <label>متن وبلاگ در صفحه اصلی</label>
                    <textarea  name="index_blog_text" class="form-control" rows="3">{{ option('index_blog_text') }}</textarea>
                </fieldset>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>ایمیل</label>
                        <input type="text" name="info_email" class="form-control" value="{{ option('info_email') }}">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>شماره موبایل</label>
                        <input type="text" name="info_mobile" class="form-control" value="{{ option('info_mobile') }}">
                    </div>
                </div>
            </div>
        </div>

        <dir class="row p-0">
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>طول جغرافیایی</label>
                        <input type="text" id="Longitude" name="info_Longitude" class="form-control" value="{{ option('info_Longitude', '46.28582686185837') }}">
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="controls">
                        <label>عرض جغرافیایی</label>
                        <input type="text" id="latitude" name="info_latitude" class="form-control" value="{{ option('info_latitude', '38.07709880960678') }}">
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div id="map"></div>
            </div>

            <div class="col-12 d-flex flex-sm-row flex-column justify-content-end mt-1">
                <button type="submit" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1">ذخیره تغییرات</button>
                
            </div>
        </dir>
    </form>
    <!-- users edit Info form ends -->
</div>

resources/views/back/partials/settings/profile-tab.blade.php
<div class="tab-pane active" id="profile" aria-labelledby="profile-tab" role="tabpanel">

    <!-- users edit media object start -->
    <div class="media mb-2">
        <a class="mr-2 my-25" href="#">
            <img id="profile-pic" src="{{ auth()->user()->imageUrl }}" alt="users avatar" class="users-avatar-shadow rounded" height="90" width="90">
        </a>
        <div class="media-body mt-50">
            
            <div class="col-12 d-flex mt-1 px-0">
                <button id="edit-image-btn" class="btn btn-primary mr-75">ویرایش تصویر</button>
            </div>
        </div>
    </div>
    <!-- users edit media object ends -->
    <!-- users edit profile form start -->
    <form id="profile-form" action="{{ route('admin.settings.profile') }}" method="POST" enctype="multipart/form-data" autocomplete="off">
        <div class="row">
            <input type="file" name="image" id="profile-image" accept="image/*" style="display: none;">
            <div class="col-12 col-sm-6">
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <div class="controls">
                            <label>نام</label>
                            <input name="first_name" type="text" class="form-control" placeholder="نام" value="{{ auth()->user()->first_name }}" required >
                        </div>
                    </div>
                    <div class="form-group col-md-6">
                        <div class="controls">
                            <label>نام خانوادگی</label>
                            <input name="last_name" type="text" class="form-control" placeholder="نام خانوادگی" value="{{ auth()->user()->last_name }}" required >
                        </div>
                    </div>

                </div>
                <div class="form-group">
                    <div class="controls">
                        <label>نام کاربری</label>
                        <input name="username" type="text" class="form-control" placeholder="نام کاربری" value="{{ auth()->user()->username }}" required >
                    </div>
                </div>
            </div>
            <div class="col-12 col-sm-6">
                <div class="form-group">
                    <div class="controls">
                        <label>گذرواژه</label>
                        <input id="password" name="password" type="text" class="form-control pw" placeholder="گذرواژه">
                    </div>
                </div>
                <div class="form-group">
                    <div class="controls">
                        <label>تکرار گذرواژه</label>
                        <input name="password_confirmation" type="text" class="form-control pw" placeholder="تکرار گذرواژه">
                    </div>
                </div>
                
            </div>
            <div class="col-12">
                <div class="alert alert-info mt-1 alert-validation-msg" role="alert">
                    <i class="feather icon-info ml-1 align-middle"></i>
                    <span>در صورتی که نمیخواهید گذرواژه تان را عوض کنید، فیلدهای گذرواژه را خالی بگذارید.</span>
                </div>
            </div>
            <div class="col-12 d-flex flex-sm-row flex-column justify-content-end mt-1">
                <button type="submit" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1">ذخیره تغییرات</button>
            </div>
        </div>
    </form>
    <!-- users edit profile form ends -->
</div>

resources/views/back/partials/settings/sizes-tab.blade.php
@if (auth()->user()->level == 'creator')
    <div class="tab-pane" id="sizes" aria-labelledby="sizes-tab" role="tabpanel">
        <!-- users edit socail form start -->
        <form id="sizes-form" action="{{ route('admin.settings.sizes') }}" method="POST">
            <div class="row">
                <div class="col-md-6">
                    <label>تصویر شاخص محصولات</label>
                    <div class="input-group mb-75">
                        <input type="text" name="sizes_product_image" class="form-control ltr"
                            value="{{ option('sizes_product_image') }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <label>تصاویر گالری محصول</label>
                    <div class="input-group mb-75">
                        <input type="text" name="sizes_product_gallery" class="form-control ltr"
                            value="{{ option('sizes_product_gallery') }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <label>لوگو</label>
                    <div class="input-group mb-75">
                        <input type="text" name="sizes_logo" class="form-control ltr"
                            value="{{ option('sizes_logo') }}">
                    </div>
                </div>
                <div class="col-md-6">
                    <label>آیکون</label>
                    <div class="input-group mb-75">
                        <input type="text" name="sizes_icon" class="form-control ltr"
                            value="{{ option('sizes_icon') }}">
                    </div>
                </div>

                <div class="col-md-6">
                    <label>تصویر شاخص پست ها</label>
                    <div class="input-group mb-75">
                        <input type="text" name="sizes_post_image" class="form-control ltr"
                            value="{{ option('sizes_post_image') }}">
                    </div>
                </div>

                <div class="col-md-6">
                    <label>تصویر شاخص آگهی ها</label>
                    <div class="input-group mb-75">
                        <input type="text" name="sizes_advertising_image" class="form-control ltr"
                            value="{{ option('sizes_advertising_image') }}">
                    </div>
                </div>

                <div class="col-12 d-flex flex-sm-row flex-column justify-content-end mt-1">
                    <button type="submit" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1">ذخیره تغییرات</button>

                </div>
            </div>
        </form>
        <!-- users edit socail form ends -->
    </div>
@endif

resources/views/back/partials/settings/social-tab.blade.php
<div class="tab-pane" id="social" aria-labelledby="social-tab" role="tabpanel">
    <!-- users edit socail form start -->
    <form id="socials-form" action="{{ route('admin.settings.socials') }}" method="POST">
        <div class="row">
            <div class="col-12 col-sm-6">

                <fieldset>
                    <label>تلگرام</label>
                    <div class="input-group mb-75">
                        
                        <input type="text" name="social_telegram" class="form-control ltr" value="{{ option('social_telegram') }}">
                        <div class="input-group-append">
                            <span class="input-group-text fa fa-telegram"></span>
                        </div>
                    </div>

                    <label>اینستاگرام</label>
                    <div class="input-group mb-75">
                        
                        <input type="text" name="social_instagram" class="form-control ltr" value="{{ option('social_instagram') }}">
                        <div class="input-group-append">
                            <span class="input-group-text feather icon-instagram"></span>
                        </div>
                    </div>

                    <label>واتساپ</label>
                    <div class="input-group mb-75">
                        
                        <input type="text" name="social_whatsapp" class="form-control ltr" value="{{ option('social_whatsapp') }}">
                        <div class="input-group-append">
                            <span class="input-group-text fa fa-whatsapp"></span>
                        </div>
                    </div>

                    <label>توییتر</label>
                    <div class="input-group mb-75">
                        <input type="text" name="social_twitter" class="form-control ltr" value="{{ option('social_twitter') }}">
                        <div class="input-group-append">
                            <span class="input-group-text feather icon-twitter"></span>
                        </div>
                    </div>
                    
                </fieldset>
            </div>
            <div class="col-12 col-sm-6">

                
                <label>فیسبوک</label>
                <div class="input-group mb-75">
                    <input type="text" name="social_facebook" class="form-control ltr" value="{{ option('social_facebook') }}">
                    <div class="input-group-append">
                        <span class="input-group-text feather icon-facebook"></span>
                    </div>
                </div>

                <label>یوتیوب</label>
                <div class="input-group mb-75">
                    <input type="text" name="social_youtube" class="form-control ltr" value="{{ option('social_youtube') }}">
                    <div class="input-group-append">
                        <span class="input-group-text fa fa-youtube"></span>
                    </div>
                </div>

                <label>لینکدین</label>
                <div class="input-group mb-75">
                    <input type="text" name="social_linkedin" class="form-control ltr" value="{{ option('social_linkedin') }}">
                    <div class="input-group-append">
                        <span class="input-group-text fa fa-linkedin"></span>
                    </div>
                </div>
            </div>
            <div class="col-12 d-flex flex-sm-row flex-column justify-content-end mt-1">
                <button type="submit" class="btn btn-primary glow mb-1 mb-sm-0 mr-0 mr-sm-1">ذخیره تغییرات</button>
                
            </div>
        </div>
    </form>
    <!-- users edit socail form ends -->
</div>