routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['namespace' => 'Auth'], function () {
    // ------------------ Authentication Routes...
    Route::post('login', 'LoginController@login');
    Route::post('logout', 'LoginController@logout')->name('logout');

    Route::get('logout', 'LoginController@logout');
});

Route::get('province/get-cities', 'ProvinceController@getCities');

Route::get('login', 'Back\MainController@login')->name('login');

// ------------------ Admin Part Routes
Route::group(['namespace' => 'Back', 'as' => 'admin.', 'prefix' => 'admin', 'middleware' => ['auth', 'Admin']], function () {

    // ------------------ MainController
    Route::get('/', 'MainController@index')->name('dashboard');
    Route::get('settings', 'MainController@settings')->name('settings');
    Route::post('settings/profile', 'MainController@profile')->name('settings.profile');
    Route::post('settings/socials', 'MainController@socials')->name('settings.socials');
    Route::post('settings/sizes', 'MainController@sizes')->name('settings.sizes');
    Route::post('settings/information', 'MainController@information')->name('settings.information');
    Route::get('get-tags', 'MainController@get_tags');

    Route::get('notifications', 'MainController@notifications')->name('notifications');

    Route::get('file-manager', 'MainController@fileManager')->name('file-manager');
    Route::get('file-manager-iframe', 'MainController@fileManagerIframe')->name('file-manager-iframe');

    // ------------------ users
    Route::resource('users', 'UserController');
    Route::get('users/export/excel', 'UserController@export')->name('users.export');

    // ------------------ widgets
    Route::resource('widgets', 'WidgetController');

    // ------------------ pictorials
    Route::resource('pictorials', 'PictorialController')->except('show');
    Route::post('pictorials/image-store', 'PictorialController@image_store');
    Route::post('pictorials/image-delete', 'PictorialController@image_delete');
    Route::get('pictorial/categories', 'PictorialController@categories')->name('pictorials.categories.index');


    // ------------------ posts
    Route::resource('posts', 'PostController')->except(['show']);
    Route::get('post/categories', 'PostController@categories')->name('posts.categories.index');

    // ------------------ videos
    Route::resource('videos', 'VideoController')->except(['show']);
    Route::get('video/categories', 'VideoController@categories')->name('videos.categories.index');


    // ------------------ categories
    Route::resource('categories', 'CategoryController')->only(['update', 'destroy', 'store']);
    Route::post('categories/sort', 'CategoryController@sort');


    // ------------------ pages
    Route::resource('pages', 'PageController')->except(['show']);

    // ------------------ menus
    Route::resource('menus', 'MenuController')->except(['edit']);
    Route::post('menus/sort', 'MenuController@sort');

    // ------------------ sliders
    Route::resource('sliders', 'SliderController')->except(['show']);
    Route::post('sliders/sort', 'SliderController@sort');

    // ------------------ banners
    Route::resource('banners', 'BannerController')->except(['show']);
    Route::post('banners/sort', 'BannerController@sort');

    // ------------------ links
    Route::resource('links', 'LinkController')->except(['show']);
    Route::post('links/sort', 'LinkController@sort');
    Route::get('links/groups', 'LinkController@groups')->name('links.groups.index');
    Route::put('links/groups/update', 'LinkController@updateGroups')->name('links.groups.update');

    // ------------------ contacts
    Route::resource('contacts', 'ContactController')->only(['index', 'show', 'destroy']);

    // ------------------ newsletters
    Route::resource('newsletters', 'NewsletterController')->only(['index', 'destroy']);
    Route::get('newsletters/export/excel', 'NewsletterController@export')->name('newsletters.export');

    // ------------------ comments
    Route::resource('comments', 'CommentController')->only(['index', 'show', 'destroy', 'update']);
});

// ------------------ Front Part Routes
Route::group(['namespace' => 'Front', 'as' => 'front.'], function () {
    // ------------------ MainController
    Route::get('/', 'MainController@index')->name('index');
    Route::get('/get-new-captcha', 'MainController@captcha');

    // ------------------ pictorials
    Route::resource('pictorials', 'PictorialController')->only(['index', 'show']);
    Route::get('pictorials/category/{category}', 'PictorialController@category')->name('pictorials.category');
    Route::get('pictorials/category-pictorials/{category}', 'PictorialController@categoryPictorials')->name('pictorials.category-pictorials');
    Route::post('pictorials/{pictorial}/comments', 'PictorialController@comments')->name('pictorial.comments');

    // ------------------ posts
    Route::resource('posts', 'PostController')->only(['index', 'show']);
    Route::get('posts/category/{category}', 'PostController@category')->name('posts.category');
    Route::post('posts/{post}/comments', 'PostController@comments')->name('post.comments');

    // ------------------ videos
    Route::resource('videos', 'VideoController')->only(['index', 'show']);
    Route::get('videos/category/{category}', 'VideoController@category')->name('videos.category');
    Route::post('videos/{video}/comments', 'VideoController@comments')->name('video.comments');
    Route::get('pages/{pages}', 'PageController@show')->name('pages.show');

    // ------------------ newsletters
    Route::resource('newsletters', 'NewsletterController')->only(['store']);

    // ------------------ contacts
    Route::resource('contact', 'ContactController')->only(['index', 'store']);
});

Route::get('/about', function () {
    return view('front.about');
});

app/Link.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Link extends Model
{
    protected $guarded = ['id'];

    public function group()
    {
        return $this->belongsTo(LinkGroup::class, 'link_group_id');
    }
}

app/Http/Controllers/Back/BannerController.php
<?php

namespace App\Http\Controllers\Back;

use App\Banner;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BannerController extends Controller
{
    public function index()
    {
        return view('back.banners.index');
    }

    public function create()
    {
        return view('back.banners.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'image' => 'mimes:jpeg,jpg,png,gif|required|max:2048',
            'group' => 'required'
        ]);

        $file = $request->image;
        $name = uniqid() . '_' . time() . '.' . $file->getClientOriginalExtension();
        $request->image->storeAs('banners', $name);

        Banner::create([
            'link'        => $request->link,
            'group'       => $request->group,
            'published'   => $request->published ? true : false,
            'image'       => '/uploads/banners/' . $name,
            'lang'        => app()->getLocale(),
        ]);

        toastr()->success('بنر با موفقیت ایجاد شد.');

        return response("success");
    }

    public function edit(Banner $banner)
    {
        return view('back.banners.edit', compact('banner'));
    }

    public function update(Banner $banner, Request $request)
    {
        $this->validate($request, [
            'image' => 'mimes:jpeg,jpg,png,gif|max:2048',
            'group' => 'required'
        ]);

        if ($request->hasFile('image')) {
            
            if ($banner->image) {
                Storage::disk('public')->delete($banner->image);
            }

            $file = $request->image;
            $name = uniqid() . '_' . time() . '.' . $file->getClientOriginalExtension();
            $request->image->storeAs('banners', $name);

            $banner->image = '/uploads/banners/' . $name;
            $banner->save();
        }

        $banner->update([
            'link'        => $request->link,
            'group'       => $request->group,
            'published'   => $request->published ? true : false,
        ]);

        toastr()->success('بنر با موفقیت ویرایش شد.');

        return response("success");
    }

    public function destroy(Banner $banner)
    {
        if ($banner->image) {
            Storage::disk('public')->delete($banner->image);
        }

        $banner->delete();

        return response('success');
    }

    public function sort(Request $request)
    {
        $this->validate($request, [
            'banners' => 'required|array'
        ]);

        $i = 1;

        foreach ($request->banners as $banner) {
            Banner::findOrFail($banner)->update([
                'ordering' => $i++,
            ]);
        };

        return response('success');
    }
}

app/Http/Controllers/Back/CategoryController.php
<?php

namespace App\Http\Controllers\Back;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class CategoryController extends Controller
{
    public $ordering = 1;

    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required|string',
            'type'  => 'required|string',
        ]);

        $category = Category::create([
            'title' => $request->title,
            'type'  => $request->type,
            'lang'  => app()->getLocale()
        ]);

        return $category;
    }
    
    public function update(Request $request, $id)
    {
        $category = Category::findOrFail($id);

        $this->validate($request, [
            'title' => 'required|string',
            'image' => 'image',
        ]);

        $category->update([
            'title' => $request->title,
        ]);

        if ($request->hasFile('image')) {
            $file = $request->image;
            $name = uniqid() . '_' . $category->id . '.' . $file->getClientOriginalExtension();
            $request->image->storeAs('categories', $name);

            if ($category->image) {
                Storage::disk('public')->delete($category->image);
            }

            $category->image = '/uploads/categories/' . $name;
            $category->save();
        }

        return $category->title;
    }

    public function destroy($id)
    {
        $category = Category::findOrFail($id);

        $category->delete();
    }

    public function sort(Request $request)
    {
        $this->validate($request, [
            'categories' => 'required|array'
        ]);

        $categories = $request->categories;

        $this->sort_category($categories);

        return 'success';
    }

    private function sort_category($categories, $category_id = null)
    {
        foreach ($categories as $category) {
            Category::find($category['id'])->update(['category_id' => $category_id, 'ordering' => $this->ordering++]);
            if (array_key_exists('children', $category)) {
                $this->sort_category($category['children'], $category['id']);
            }
        }
    }
}

app/Http/Controllers/Back/CommentController.php
<?php

namespace App\Http\Controllers\Back;

use App\Comment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function index(Request $request)
    {
        $comments = Comment::filter($request)->paginate(15);

        return view('back.comments.index', compact('comments'));
    }

    public function show(comment $comment)
    {
        return view('back.comments.show', compact('comment'))->render();
    }

    public function destroy(comment $comment)
    {
        $comment->delete();

        return response('success');
    }

    public function update(Comment $comment, Request $request)
    {
        $this->validate($request, [
            'status' => 'required',
            'body'   => 'required',
            'replay' => 'nullable|string',
        ]);

        $comment->update([
            'body'   => $request->body,
            'status' => $request->status
        ]);

        if ($request->replay) {
            $comment->commentable->comments()->create([
                'lang'       => app()->getLocale(),
                'body'       => $request->replay,
                'user_id'    => auth()->user()->id,
                'status'     => 'accepted',
                'comment_id' => $comment->id,
            ]);
        }

        return response($comment);
    }
}

app/Http/Controllers/Back/ContactController.php
<?php

namespace App\Http\Controllers\Back;

use App\Contact;
use App\Http\Controllers\Controller;

class ContactController extends Controller
{
    public function index()
    {
        $contacts = Contact::latest()->paginate(15);

        return view('back.contacts.index', compact('contacts'));
    }

    public function show(Contact $contact)
    {
        return view('back.contacts.show', compact('contact'))->render();
    }

    public function destroy(Contact $contact)
    {
        $contact->delete();

        return response('success');
    }
}

app/Http/Controllers/Back/LinkController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Link;
use App\LinkGroup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class LinkController extends Controller
{
    public function index()
    {
        $groups = LinkGroup::where('lang', app()->getLocale())->get();

        return view('back.links.index', compact('groups'));
    }

    public function create()
    {
        $groups = LinkGroup::where('lang', app()->getLocale())->get();

        return view('back.links.create', compact('groups'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'title'         => 'required',
            'link'          => 'required',
            'link_group_id' => 'required|exists:link_groups,id',
        ]);

        Link::create([
            'title'            => $request->title,
            'link'             => $request->link,
            'link_group_id'    => $request->link_group_id,
            'ordering'         => Link::max('ordering') + 1,
        ]);

        toastr()->success('لینک با موفقیت ایجاد شد.');

        return response("success");
    }

    public function edit(Link $link)
    {
        $groups = LinkGroup::where('lang', app()->getLocale())->get();

        return view('back.links.edit', compact('link', 'groups'));
    }

    public function update(Link $link, Request $request)
    {
        $this->validate($request, [
            'title'         => 'required',
            'link'          => 'required',
            'link_group_id' => 'required|exists:link_groups,id',
        ]);

        $link->update([
            'title'            => $request->title,
            'link'             => $request->link,
            'link_group_id'    => $request->link_group_id,
        ]);

        toastr()->success('لینک با موفقیت ویرایش شد.');

        return response("success");
    }

    public function destroy(Link $link)
    {
        if ($link->image) {
            Storage::disk('public')->delete($link->image);
        }

        $link->delete();

        return response('success');
    }

    public function sort(Request $request)
    {
        $this->validate($request, [
            'links' => 'required|array'
        ]);

        $i = 1;

        foreach ($request->links as $link) {
            Link::findOrFail($link)->update([
                'ordering' => $i++,
            ]);
        };

        return response('success');
    }

    // groups methods

    public function groups()
    {
        $groups = LinkGroup::where('lang', app()->getLocale())->get();

        return view('back.links.groups', compact('groups'));
    }

    public function updateGroups(Request $request)
    {
        $request->validate([
            'groups' => 'required|array',
        ]);

        foreach ($request->groups as $key => $value) {
            LinkGroup::where('id', $key)->update([
                'title' => $value
            ]);
        }

        return response('success');
    }
}

app/Http/Controllers/Back/NewsletterController.php
<?php

namespace App\Http\Controllers\Back;

use App\Exports\NewslettersExport;
use App\Http\Controllers\Controller;
use App\Newsletter;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Http\Request;

class NewsletterController extends Controller
{
    public function index()
    {
        $newsletters = Newsletter::latest()->paginate(15);

        return view('back.newsletters.index', compact('newsletters'));
    }

    public function destroy(Newsletter $newsletter)
    {
        $newsletter->delete();

        return response('success');
    }

    public function export() 
    {
        return Excel::download(new NewslettersExport, 'newsletters.xlsx');
    }
}

resources/views/back/links/create.blade.php
@extends('back.layouts.master')

@push('styles')
    <link rel="stylesheet" type="text/css" href="/back/app-assets/plugins/jquery-ui/jquery-ui.css">
@endpush

@section('content')

<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb no-border">
                                <li class="breadcrumb-item">مدیریت
                                </li>
                                <li class="breadcrumb-item">مدیریت لینک ها
                                </li>
                                <li class="breadcrumb-item active">ایجاد لینک 
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="content-body">
            <!-- Description -->
            <section class="card">
                <div class="card-header">
                    <h4 class="card-title">ایجاد لینک  جدید</h4>
                </div>
                
                <div id="main-card" class="card-content">
                    <div class="card-body">
                        <div class="col-12 col-md-10 offset-md-1">
                            <form class="form" id="link-create-form" action="{{ route('admin.links.store') }}" method="link">
                                @csrf
                                <div class="form-body">
                                    <div class="row">
                                        
                                        <div class="col-md-6 col-12">
                                            <div class="form-group">
                                                <label>عنوان </label>
                                                <input type="text" class="form-control" name="title">
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-12">
                                            <div class="form-group">
                                                <label>لینک </label>
                                                <input type="text" class="form-control link-link ltr" name="link">
                                            </div>
                                        </div>
                                        
                                    </div>
                                    
                                    <div class="row">
                                        
                                        <div class="col-12 col-md-6">
                                            <div class="form-group">
                                                <label>گروه</label>
                                                <select class="form-control" name="link_group_id">
                                                    @foreach($groups as $group)
                                                        <option value="{{ $group->id }}">{{ $group->title }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 text-right">
                                            <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">ایجاد لینک </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Description -->
            
        </div>
    </div>
</div>

@endsection

@push('scripts') 
    <script src="/back/app-assets/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="/back/app-assets/plugins/jquery-validation/localization/messages_fa.min.js"></script>
    <script src="/back/app-assets/plugins/jquery-ui/jquery-ui.js"></script>

    <script>
        var pages =  [
            @foreach($pages as $page)
                "/pages/{{ $page }}",
            @endforeach
        ];
    </script>

    <script src="/back/assets/js/pages/links/create.js"></script>
@endpush

resources/views/back/links/edit.blade.php
@extends('back.layouts.master')

@push('styles')
    <link rel="stylesheet" type="text/css" href="/back/app-assets/plugins/jquery-ui/jquery-ui.css">
@endpush

@section('content')

<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb no-border">
                                <li class="breadcrumb-item">مدیریت
                                </li>
                                <li class="breadcrumb-item">مدیریت لینک ها
                                </li>
                                <li class="breadcrumb-item active">ویرایش لینک 
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="content-body">
            <!-- Description -->
            <section class="card">
                <div class="card-header">
                    <h4 class="card-title">ویرایش لینک  </h4>
                </div>
                
                <div id="main-card" class="card-content">
                    <div class="card-body">
                        <div class="col-12 col-md-10 offset-md-1">
                            <form class="form" id="link-edit-form" action="{{ route('admin.links.update', ['link' => $link]) }}" method="post">
                                @csrf
                                @method('put')
                                <div class="form-body">
                                    <div class="row">
                                        
                                        <div class="col-md-6 col-12">
                                            <div class="form-group">
                                                <label>عنوان </label>
                                                <input type="text" class="form-control link-link" name="title" value="{{ $link->title }}">
                                            </div>
                                        </div>
                                        <div class="col-md-6 col-12">
                                            <div class="form-group">
                                                <label>لینک </label>
                                                <input type="text" class="form-control link-link ltr" name="link" value="{{ $link->link }}">
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        
                                        <div class="col-12 col-md-6">
                                            <div class="form-group">
                                                <label>گروه</label>
                                                <select class="form-control" name="link_group_id">
                                                    @foreach($groups as $group)
                                                        <option value="{{ $group->id }}" {{ $link->group->id == $group->id ? 'selected' : '' }} >{{ $group->title }}</option>
                                                    @endforeach
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-12 text-right">
                                            <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">ویرایش لینک </button>
                                        </div>
                                    </div>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </section>
            <!--/ Description -->
            
        </div>
    </div>
</div>

@endsection

@push('scripts') 
    <script src="/back/app-assets/plugins/jquery-validation/jquery.validate.min.js"></script>
    <script src="/back/app-assets/plugins/jquery-validation/localization/messages_fa.min.js"></script>
    <script src="/back/app-assets/plugins/jquery-ui/jquery-ui.js"></script>

    <script>
        var pages =  [
            @foreach($pages as $page)
                "/pages/{{ $page }}",
            @endforeach
        ];
    </script>

    <script src="/back/assets/js/pages/links/edit.js"></script>
@endpush

resources/views/back/links/groups.blade.php
@extends('back.layouts.master')

@push('styles')
    <link rel="stylesheet" type="text/css" href="/back/app-assets/plugins/jquery-ui/jquery-ui.css">
@endpush

@section('content')

<div class="app-content content">
    <div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb no-border">
                                <li class="breadcrumb-item">مدیریت
                                </li>
                                <li class="breadcrumb-item">مدیریت لینک ها
                                </li>
                                <li class="breadcrumb-item active">لیست گروه ها 
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="content-body">
            <!-- Description -->
            <section class="card">
                <div class="card-header">
                    <h4 class="card-title">ایجاد لینک  جدید</h4>
                </div>
                
                <div id="main-card" class="card-content">
                    <div class="card-body">
                        <div class="col-12 col-md-10 offset-md-1">
                            <form class="form" id="link-groups-form" action="{{ route('admin.links.groups.update') }}" method="post">
                                @csrf
                                @method('put')
                                <div class="form-body">
                                    <div class="row">
                                        @foreach($groups as $group)
                                            <div class="col-md-6 col-12">
                                                <div class="form-group">
                                                    <label>عنوان گروه {{ $loop->iteration }}</label>
                                                    <input type="text" class="form-control" name="groups[{{ $group->id }}]" value="{{ $group->title }}" required>
                                                </div>
                                            </div>
                                        @endforeach
                                        
                                    </div>

                                    <div class="row">
                                        <div class="col-12 text-right">
                                            <button type="submit" class="btn btn-primary mr-1 mb-1 waves-effect waves-light">ذخیره تغییرات </button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Description -->
            
        </div>
    </div>
</div>

@endsection

@push('scripts') 
    <script src="/back/assets/js/pages/links/groups.js"></script>
@endpush